### ISSUE TITLE
感谢大神分享

### ISSUE THREAD

**Issue by ipengyo** [imfly/bitcoin-on-nodejs#1]
你的知识 从浅到深 仔仔细细  ，小弟读了十分敬佩。。

**Comment by imfly** [comment]
客气了，喜欢就好，有用就好。

文章，因为与实际项目紧密结合，所以写起来操作性更强些。建议同时关注并加入项目，进步会更快些。

人人都说，在币圈，中国人没有话语权，因为技术不行。我想通过分享，把更多喜欢加密货币的小伙伴聚拢起来，让大家共同研究、学习、提高。总有一天，在加密货币领域，会有更多中国的牛人出现。

现在 区块链俱乐部 <http://chainclub.org> 已经有了很多小伙伴，还是有希望的。
